import secrets
import os

def generate_secrets():
    """Generates a secure .env file for ZeroCraftr."""
    
    print("Generating secure secrets for ZeroCraftr...")
    
    # Generate secure keys
    secret_key = secrets.token_hex(32)
    postgres_password = secrets.token_urlsafe(16)
    
    env_content = f"""# ZeroCraftr Environment Variables
# Generated by scripts/setup_secrets.py

# Project
PROJECT_NAME=ZeroCraftr
API_V1_STR=/api/v1
SECRET_KEY={secret_key}
ACCESS_TOKEN_EXPIRE_MINUTES=30

# CORS
BACKEND_CORS_ORIGINS=["http://localhost:3000", "http://localhost:8000"]

# Database
POSTGRES_SERVER=db
POSTGRES_USER=postgres
POSTGRES_PASSWORD={postgres_password}
POSTGRES_DB=zerocraftr
SQLALCHEMY_DATABASE_URI=postgresql+asyncpg://postgres:{postgres_password}@db:5432/zerocraftr

# MQTT
MQTT_BROKER_HOST=mqtt
MQTT_BROKER_PORT=1883
MQTT_CLIENT_ID=zerocraftr-backend

# MLflow
MLFLOW_TRACKING_URI=http://mlflow:5000
"""

    # Write to .env file
    env_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), '.env')
    
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print(f"Success! Secure .env file created at: {env_path}")
    print(f"Generated SECRET_KEY: {secret_key[:5]}...")
    print(f"Generated POSTGRES_PASSWORD: {postgres_password[:5]}...")
    print("\nIMPORTANT: Update your docker-compose.yml to use these variables if not already configured.")

if __name__ == "__main__":
    generate_secrets()
